server:
  port: 8082

app:
  inventoryBaseUrl: ${INVENTORY_BASE_URL:http://localhost:8000}
  inventoryTopic: ${INVENTORY_TOPIC:inventory_data}
  inventoryDlqTopic: ${INVENTORY_DLQ_TOPIC:dlq_inventory_data}

spring:
  application:
    name: inventory-producer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
        linger.ms: 5
        batch.size: 32768
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  retry:
    instances:
      inventoryApi:
        max-attempts: 3
        wait-duration: 1s
