name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      kafka:
        image: bitnami/kafka:3.7
        ports:
          - 9092:9092
        env:
          KAFKA_ENABLE_KRAFT: "yes"
          KAFKA_CFG_PROCESS_ROLES: broker,controller
          KAFKA_CFG_NODE_ID: 1
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
        options: >-
          --health-cmd "bash -c 'echo > /dev/tcp/127.0.0.1/9092'" 
          --health-interval 5s --health-timeout 2s --health-retries 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & Test (Java Producers)
        working-directory: java-producers
        run: mvn -q -DskipTests=false test

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        working-directory: python-consumers/analytics_consumer
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        working-directory: python-consumers/analytics_consumer
        run: pytest --cov=analytics_consumer --cov-report=xml --cov-report=term -q

      - name: Upload Java coverage (CRM)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crm-jacoco-report
          path: |
            java-producers/crm-producer/target/jacoco-report/**
            java-producers/crm-producer/target/site/jacoco/jacoco.xml

      - name: Upload Java coverage (Inventory)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inventory-jacoco-report
          path: |
            java-producers/inventory-producer/target/jacoco-report/**
            java-producers/inventory-producer/target/site/jacoco/jacoco.xml

      - name: Upload Python coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: python-consumers/analytics_consumer/coverage.xml
